http:
  port: 9774
  timeout: 30
handlers:
- provider: gitlab
  route: "/gitlab/webhook"
  exporters:
  - provider: telegram
    token: 5577541047:AAGeDDYUK73aWNCT2e91xJpULVx6wbhSxuA
    chats:
    - -543537020
  templates:
  - push: 'The test push message. User pushed: {{.user_name}}'
  - build: 'The test build message. Build name: {{.build_name}}'