http:
  port: 9774
  timeout: 30
vcshosting:
  provider: gitlab
  options:
    token: <your gitlab token>
    url: https://your-gitlab-address
messenger:
  provider: telegram
  options:
    token: <your telegram bot token>
    chatIds:
    - 123
handlers:
- route: "/gitlab/merge-request"
  action: merge_request
- route: "/gitlab/deployment"
  action: deployment