http:
  port: 9774
  timeout: 30
handlers:
- provider: gitlab
  route: /gitlab/webhook
  exporters:
  - provider: telegram
  templates:
  - push: 'The test push message. User pushed: {{.user_name}}'
  - build: 'The test build message. Build name: {{.build_name}}'