http:
  port: 9774
  timeout: 30
handlers:
- vcshosting:
    provider: gitlab
    options:
      token: glpat-4L9rqBQdsHzj18fG7-qe
      url: https://gitlab.emsoft.ru
  route: "/gitlab/merge-request"
  action: merge_request
  exporters:
  - provider: telegram
    options:
      token: 5577541047:AAGeDDYUK73aWNCT2e91xJpULVx6wbhSxuA
      chatIds:
      - 877240015
- vcshosting:
    provider: gitlab
    options:
      token: glpat-4L9rqBQdsHzj18fG7-qe
      url: https://gitlab.emsoft.ru
  route: "/gitlab/deployment"
  action: deployment
  exporters:
  - provider: telegram
    options:
      token: 5577541047:AAGeDDYUK73aWNCT2e91xJpULVx6wbhSxuA
      chatIds:
      - 877240015